

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # Kui React kasutab keskkonnamuutujat API URL-i jaoks, seadista see siin:

      - REACT_APP_API_URL=http://server:5000/api
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
